spring:
  datasource:
    url: jdbc:mysql://honblack-blog-dev.cyuldtz8tivz.ap-northeast-1.rds.amazonaws.com/honblack
    username: honblack
    password: ''
    driverClassName: com.mysql.jdbc.Driver
flyway:
  enabled: false
