spring:
  datasource:
    url: jdbc:mysql://honblack-blog-dev.cyuldtz8tivz.ap-northeast-1.rds.amazonaws.com/honblack
    username: honblack
    password: ''
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
flyway:
  enabled: false
mybatis:
  mapper-locations: classpath:repository/*.xml
  configuration:
    map-underscore-to-camel-case: true