spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
  thymeleaf:
    mode: LEGACYHTML5
mybatis:
  mapper-locations: classpath:repository/*.xml
  configuration:
    map-underscore-to-camel-case: true